### ISSUE TITLE
Only testing .txt files does not cover enough test cases

### ISSUE THREAD

**Issue by jssmk** [Digital-Preservation-Finland/dpres-siptools#1]
https://github.com/Digital-Preservation-Finland/dpres-siptools/blob/b1345a5d27972512940a8809e9f0381cb73cae1d/tests/scripts/test_import_object.py#L12

**Comment by vpv-csc** [comment]
Going through old issues due to new activity on Github.

We now have
https://github.com/Digital-Preservation-Finland/dpres-siptools/blob/f730f40e4ac5bd9f4f613859177d4cc387aab501/tests/scripts/test_import_object.py#L220
which tests more file types. Even more tests are at https://github.com/Digital-Preservation-Finland/file-scraper which is now used by import-object.
