### ISSUE TITLE
techmd might not have key format

### ISSUE THREAD

**Issue by jssmk** [Digital-Preservation-Finland/dpres-siptools#2]
https://github.com/Digital-Preservation-Finland/dpres-siptools/blob/b1345a5d27972512940a8809e9f0381cb73cae1d/siptools/scripts/import_object.py#L133

Gives me KeyError: 'format'
Should give warning of possible missing format_name
(skip_inspection flag set on)

**Comment by vpv-csc** [comment]
Going through old issues due to new activity on Github.

The structure of the code has changed and https://github.com/Digital-Preservation-Finland/file-scraper is now used by import-object.

Sorry we didn't answer in time. If you find issues with the current versions of the code, please file new issues.
